# Generated by Django 4.1.2 on 2022-11-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.AddField(
            model_name='author',
            name='_rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
    ]
